env:
  browser: true
  jquery : true
  node   : true
  es6    : true

extends:
  - airbnb/base

plugins:
  - babel

rules:
  indent:
    - error
    - 2
  no-var: error
  wrap-iife: off
  func-names: off # Require Function Expressions to have a Name
  no-bitwise: off
  vars-on-top: off
  no-plusplus: off
  no-lonely-if: off
  prefer-const: off
  comma-dangle: off
  padded-blocks: off
  prefer-template: off
  no-param-reassign: off
  no-nested-ternary: off # Disallow Nested Ternaries
  no-mixed-operators: off
  operator-assignment: off
  no-floating-decimal: off
  no-use-before-define: off
  no-underscore-dangle: off
  class-methods-use-this: off
  no-template-curly-in-string: off

  import/imports-first: off
  import/prefer-default-export: off

  no-multi-spaces:
    - error
    - exceptions:
        ImportDeclaration : true
        VariableDeclarator: true
        AssignmentExpression: true

  no-unused-expressions:
    - error
    -
      allowShortCircuit: true
      allowTernary: true

  quote-props:
    - error
    - consistent-as-needed

  no-restricted-syntax:
    - error
    - WithStatement
