language: node_js

node_js:
  - 0.12

script:
  - npm run-script lint
  - npm test

install: npm install

after_script: NODE_ENV=test istanbul cover _mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage
